/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.yueli.userinterface.careteamadminworkarea;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.yueli.business.Business;
import org.yueli.business.enterprise.Enterprise;
import org.yueli.business.network.Network;
import org.yueli.business.organization.CareTeamOrganization;
import org.yueli.business.organization.Organization;
import org.yueli.business.schedule.Schedule;
import org.yueli.business.useraccount.UserAccount;
import org.yueli.business.workqueue.OperationRequest;
import org.yueli.business.workqueue.WorkRequest;

/**
 *
 * @author Lydia
 */
public class ViewOperationRequest extends javax.swing.JPanel {

    /**
     * Creates new form ViewOperationRequest
     */
    private JPanel userProcessContainer;
    private Business business;
    private Network network;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    public ViewOperationRequest(JPanel userProcessContainer, Business business, Network network, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.network = network;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        populateCareTeamRequestTable();
    }
    
    public void populateCareTeamRequestTable(){
        DefaultTableModel model = (DefaultTableModel)careTeamRequestTable.getModel();
        model.setRowCount(0);
        for(WorkRequest workRequest : business.getWorkQueue().getWorkRequestList()){
            if(workRequest instanceof OperationRequest){
                Object row[] = new Object[6];
                row[0] = workRequest.getRequestID();
                row[1] = ((OperationRequest)workRequest).getCareTeamID();
                row[2] = ((OperationRequest)workRequest).getBeginningTime();
                row[3] = ((OperationRequest)workRequest).getEndTime();
                row[4] = ((OperationRequest)workRequest).getDoctorName();
                row[5] = ((OperationRequest)workRequest).getOperationRequestStatus();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        careTeamRequestTable = new javax.swing.JTable();
        approveJButton = new javax.swing.JButton();

        careTeamRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Request Care Team Number", "Beginning Time", "End Time", "Doctor Name", "Operation Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(careTeamRequestTable);
        if (careTeamRequestTable.getColumnModel().getColumnCount() > 0) {
            careTeamRequestTable.getColumnModel().getColumn(0).setResizable(false);
            careTeamRequestTable.getColumnModel().getColumn(1).setResizable(false);
            careTeamRequestTable.getColumnModel().getColumn(2).setResizable(false);
            careTeamRequestTable.getColumnModel().getColumn(3).setResizable(false);
            careTeamRequestTable.getColumnModel().getColumn(4).setResizable(false);
            careTeamRequestTable.getColumnModel().getColumn(5).setResizable(false);
        }

        approveJButton.setText("Approve");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(approveJButton)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(approveJButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = careTeamRequestTable.getSelectedRow();
        if(selectedRow <0 ){
            JOptionPane.showMessageDialog(null, "Please select a row to continue!");
        }
        else{
            OperationRequest operationRequest = (OperationRequest) careTeamRequestTable.getValueAt(selectedRow, 0);
            for(Organization organization : business.getOrganizationDirectory().getOrganizationList()){
                if(organization instanceof CareTeamOrganization){
                    for(Schedule schedule : ((CareTeamOrganization)organization).getScheduleDirectory().getScheduleList()){
                        Date requestBeginningTime = operationRequest.getBeginningTime();
                       Date requestEndTime = operationRequest.getEndTime();
                       ((CareTeamOrganization)organization).getScheduleDirectory().addSchedule(new Schedule(requestEndTime, requestEndTime, null, Schedule.ScheduleType.CareTeam));
                       operationRequest.setCareTeamRequestIsCompeleted(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_approveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveJButton;
    private javax.swing.JTable careTeamRequestTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
