/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.yueli.userinterface.doctorworkarea;

import javax.swing.JPanel;
import org.yueli.business.Business;
import org.yueli.business.enterprise.Enterprise;
import org.yueli.business.enterprise.HospitalEnterprise;
import org.yueli.business.network.Network;
import org.yueli.business.room.OperationRoom;
import org.yueli.business.room.Room;
import org.yueli.business.useraccount.UserAccount;
import org.yueli.business.workqueue.OperationRequest;
import org.yueli.business.workqueue.WorkRequest;
import org.yueli.userinterface.schedule.SchedulePanel;

/**
 *
 * @author Lydia
 */
public class ViewAndRequestOperationRoom extends javax.swing.JPanel {

    /**
     * Creates new form ViewAndRequestRoomSchedule
     */
    private JPanel userProcessContainer;
    private Business business;
    private Network network;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public ViewAndRequestOperationRoom(JPanel userProcessContainer, Business business, Network network, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.network = network;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        populateOperationRoomCombo();
    }
    
    public void populateOperationRoomCombo(){
        operationRoomNumberCombo.removeAllItems();
        if(enterprise instanceof HospitalEnterprise){
            for(Room room : enterprise.getRoomDirectory().getRoomList()){
                if(room.getType().equals(Room.RoomType.OperationRoom)){
                    operationRoomNumberCombo.addItem(((OperationRoom)room).getOperationRoomNumber());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        operationRoomNumberCombo = new javax.swing.JComboBox();
        operationRoomScheduleJPanel = new javax.swing.JPanel();
        requestOperationRoomJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        requestRoomNumberJTextField = new javax.swing.JTextField();

        jLabel1.setText("Operation Room Number: ");

        operationRoomScheduleJPanel.setLayout(new java.awt.BorderLayout());

        requestOperationRoomJButton.setText("Request Operation Room");
        requestOperationRoomJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestOperationRoomJButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Request Room Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(operationRoomNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(operationRoomScheduleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(requestRoomNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(requestOperationRoomJButton)
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operationRoomNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(operationRoomScheduleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(requestRoomNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(requestOperationRoomJButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        OperationRoom or = (OperationRoom)operationRoomNumberCombo.getSelectedItem();
        if (operationRoomNumberCombo.getSelectedItem() != null)
            operationRoomScheduleJPanel = new SchedulePanel(or.getScheduleDirectory().getScheduleList());
    }// </editor-fold>//GEN-END:initComponents

    private void requestOperationRoomJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestOperationRoomJButtonActionPerformed
        // TODO add your handling code here:
        String operationRoom = requestRoomNumberJTextField.getText();
        for(WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList()){
            if(workRequest instanceof OperationRequest){
                if(userAccount.getPerson().getFirstName().equals(workRequest.getSender())){
                    ((OperationRequest)workRequest).setOperationRoomNumber(operationRoom);
                    ((OperationRequest)workRequest).setOperationRoomRequestIsCompeleted(false);
                }
            }
        }
    }//GEN-LAST:event_requestOperationRoomJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox operationRoomNumberCombo;
    private javax.swing.JPanel operationRoomScheduleJPanel;
    private javax.swing.JButton requestOperationRoomJButton;
    private javax.swing.JTextField requestRoomNumberJTextField;
    // End of variables declaration//GEN-END:variables
}
