/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.yueli.userinterface.warehouseworkarea;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.yueli.business.Business;
import org.yueli.business.enterprise.Enterprise;
import org.yueli.business.enterprise.FoundingAcademicMedicalCenter;
import org.yueli.business.enterprise.HospitalEnterprise;
import org.yueli.business.enterprise.PrimaryCare;
import org.yueli.business.inventory.InventoryItem;
import org.yueli.business.network.Network;
import org.yueli.business.order.Order;
import org.yueli.business.order.OrderItem;
import org.yueli.business.organization.Organization;
import org.yueli.business.organization.WarehouseOrganization;
import org.yueli.business.room.Room;
import org.yueli.business.room.StorageRoom;
import org.yueli.business.useraccount.UserAccount;

/**
 *
 * @author Lydia
 */

@SuppressWarnings("unchecked")
public class AssignDevice extends javax.swing.JPanel {

    /**
     * Creates new form ArrangeDevice
     */
    private JPanel userProcessContainer;
    private Business business;
    private Network network;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    public AssignDevice(JPanel userProcessContainer, Business business, Network network, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.network = network;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = userAccount.getOrganization();
        populateDeviceTable();
       populateRoomTable();
     
    }
    
    public void populateDeviceTable(){
        DefaultTableModel model = (DefaultTableModel)deviceTable.getModel();
        model.setRowCount(0);
        
        for(Order order : business.getMasterOrderDirectory().getMasterOrderList()){
            for(OrderItem orderItem : order.getOrderItemList()){
                if(!orderItem.getInventoryItem().getDevice().isIsAssigned()){
                    Object row[] = new Object[2];
                    row[0] = orderItem;
                    row[1] = orderItem.getInventoryItem().getDevice().getDeviceID();
                    model.addRow(row);
                }
            }
        }
    }

    public void populateRoomTable(){
        DefaultTableModel model = (DefaultTableModel)storageRoomTable.getModel();
        model.setRowCount(0);
        
        for(Room room :((WarehouseOrganization)organization).getRoomDirectory().getRoomList()){
            if(room.getType() == Room.RoomType.StorageRoom){
                Object row[] = new Object[3];
                row[0] = (StorageRoom)room;
                row[1] = ((StorageRoom)room).getStorageRoomNumber();
                row[2] = ((StorageRoom)room).getStorageRoomStatus();
                model.addRow(row);
             }
        }
        
    
    }
    

    
    public void populateAssignDeviceTable(){
    
        DefaultTableModel model = (DefaultTableModel)assignDeviceTable.getModel();
        model.setRowCount(0);
        if(enterprise instanceof HospitalEnterprise ){
            for(InventoryItem inventoryItem : ((HospitalEnterprise)enterprise).getInventory().getInventoryItemList()){
                Object row[] = new Object[3];
                row[0] = inventoryItem.getDevice().getLocation();
                row[1] = inventoryItem.getDevice().getDeviceName();
                row[2] = inventoryItem.getQuantity();
                model.addRow(row);
            }
        }
        

        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        deviceTable = new javax.swing.JTable();
        assignRoomJButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        assignDeviceTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        storageRoomTable = new javax.swing.JTable();
        roomNumberJTextField = new javax.swing.JTextField();

        deviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device Name", "Device ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deviceTable);
        if (deviceTable.getColumnModel().getColumnCount() > 0) {
            deviceTable.getColumnModel().getColumn(0).setResizable(false);
            deviceTable.getColumnModel().getColumn(1).setResizable(false);
            deviceTable.getColumnModel().getColumn(1).setHeaderValue("Room Type");
        }

        assignRoomJButton.setText("Assign to a Storage Room");
        assignRoomJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignRoomJButtonActionPerformed(evt);
            }
        });

        assignDeviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Device Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(assignDeviceTable);
        if (assignDeviceTable.getColumnModel().getColumnCount() > 0) {
            assignDeviceTable.getColumnModel().getColumn(0).setResizable(false);
            assignDeviceTable.getColumnModel().getColumn(1).setResizable(false);
            assignDeviceTable.getColumnModel().getColumn(2).setResizable(false);
        }

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Room Number: ");

        storageRoomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Storage Room Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(storageRoomTable);
        if (storageRoomTable.getColumnModel().getColumnCount() > 0) {
            storageRoomTable.getColumnModel().getColumn(0).setResizable(false);
            storageRoomTable.getColumnModel().getColumn(1).setResizable(false);
            storageRoomTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(assignRoomJButton)
                        .addGap(132, 132, 132)
                        .addComponent(refreshJButton)
                        .addGap(40, 40, 40)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(roomNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshJButton))
                    .addComponent(assignRoomJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignRoomJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignRoomJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = deviceTable.getSelectedRow();
        String roomNumber = roomNumberJTextField.getText();
        if(selectedRow <0 ){
            JOptionPane.showMessageDialog(null, "Please select a row to continue!");
        }
        else{
            OrderItem orderItem = (OrderItem)deviceTable.getValueAt(selectedRow, 0);
            orderItem.getInventoryItem().getDevice().setLocation(roomNumber);
//            Room assignRoomNumber = (Room)roomNumberCombo.getSelectedItem();
//            inventoryItem.getDevice().setLocation(((StorageRoom)assignRoomNumber).getStorageRoomNumber());
           orderItem.getInventoryItem().getDevice().setIsAssigned(true);
            populateAssignDeviceTable();
//            populateRoomTable();
            
        }
    }//GEN-LAST:event_assignRoomJButtonActionPerformed

    
    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateAssignDeviceTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assignDeviceTable;
    private javax.swing.JButton assignRoomJButton;
    private javax.swing.JTable deviceTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTextField roomNumberJTextField;
    private javax.swing.JTable storageRoomTable;
    // End of variables declaration//GEN-END:variables
}
