/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.yueli.userinterface.warehouseworkarea;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.yueli.business.enterprise.Enterprise;
import org.yueli.business.network.Network;
import org.yueli.business.room.Room;
import org.yueli.business.room.StorageRoom;
import org.yueli.business.useraccount.UserAccount;

/**
 *
 * @author Lydia
 */
public class ManageStorageRoom extends javax.swing.JPanel {

    /**
     * Creates new form ManageRoom
     */
    private String status;
    private JPanel userProcessContainer;
    private Network network;
    private Enterprise enterprise;
    private UserAccount userAccount;   
    
            
    public ManageStorageRoom(JPanel userProcessContainer, Network network,Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        
        roomNumberJLabel.setVisible(false);
        roomNumberJTextField.setVisible(false);
        roomStatusJLabel.setVisible(false);
        noteJLabel.setVisible(false);
        emptyJRadioButton.setVisible(false);
        fullJRadioButton.setVisible(false);
        doneJButton.setVisible(false);
        submitJButton.setVisible(false);
        
        populateRoomTable();
    }
    
    public void populateRoomTable(){
        DefaultTableModel model = (DefaultTableModel)storageRoomTable.getModel();
        model.setRowCount(0);
        for(Room room : enterprise.getRoomDirectory().getRoomList()){
            if(room.getType() == Room.RoomType.StorageRoom){
                Object row[] = new Object[3];
                row[0] = room.getRoomID();
                row[1] = ((StorageRoom)room).getStorageRoomNumber();
                row[2] = ((StorageRoom)room).getStorageRoomStatus();
                model.addRow(row);
             }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        storageRoomTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        editJButton = new javax.swing.JButton();
        roomNumberJLabel = new javax.swing.JLabel();
        roomNumberJTextField = new javax.swing.JTextField();
        roomStatusJLabel = new javax.swing.JLabel();
        emptyJRadioButton = new javax.swing.JRadioButton();
        fullJRadioButton = new javax.swing.JRadioButton();
        doneJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        noteJLabel = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();

        storageRoomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(storageRoomTable);
        if (storageRoomTable.getColumnModel().getColumnCount() > 0) {
            storageRoomTable.getColumnModel().getColumn(0).setResizable(false);
            storageRoomTable.getColumnModel().getColumn(1).setResizable(false);
            storageRoomTable.getColumnModel().getColumn(2).setResizable(false);
        }

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        editJButton.setText("Edit");
        editJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJButtonActionPerformed(evt);
            }
        });

        roomNumberJLabel.setText("Room Number: ");

        roomNumberJTextField.setEditable(false);

        roomStatusJLabel.setText("Room Status:");

        buttonGroup1.add(emptyJRadioButton);
        emptyJRadioButton.setText("Empty");
        emptyJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyJRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(fullJRadioButton);
        fullJRadioButton.setText("Full");
        fullJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullJRadioButtonActionPerformed(evt);
            }
        });

        doneJButton.setText("Done");
        doneJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        noteJLabel.setText("(*Begin with \"S\")");

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doneJButton)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(231, 231, 231)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(roomStatusJLabel)
                                .addComponent(roomNumberJLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(roomNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(noteJLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emptyJRadioButton)
                                        .addComponent(fullJRadioButton)))))))
                .addComponent(refreshJButton)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(addJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editJButton)))
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(refreshJButton)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJButton)
                    .addComponent(editJButton))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNumberJLabel)
                    .addComponent(roomNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noteJLabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomStatusJLabel)
                    .addComponent(emptyJRadioButton))
                .addGap(18, 18, 18)
                .addComponent(fullJRadioButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneJButton)
                    .addComponent(submitJButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emptyJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyJRadioButtonActionPerformed
        // TODO add your handling code here:
        status = "Empty";
    }//GEN-LAST:event_emptyJRadioButtonActionPerformed

    private void fullJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullJRadioButtonActionPerformed
        // TODO add your handling code here:
        status = "Full";
    }//GEN-LAST:event_fullJRadioButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        roomNumberJLabel.setVisible(true);
        roomNumberJTextField.setVisible(true);
        roomNumberJTextField.setEditable(true);
        noteJLabel.setVisible(true);
        roomStatusJLabel.setVisible(true);
        emptyJRadioButton.setVisible(true);
        fullJRadioButton.setVisible(true);
        submitJButton.setVisible(true);
        
        
    }//GEN-LAST:event_addJButtonActionPerformed

    private void doneJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = storageRoomTable.getSelectedRow();
        StorageRoom storageRoom = (StorageRoom)storageRoomTable.getValueAt(selectedRow, 0);
        storageRoom.setStorageRoomStatus(status);
        if(status.equals("Empty")){
            storageRoom.setIsFull(false);
        }
        if(status.equals("Full")){
            storageRoom.setIsFull(true);
        }
        populateRoomTable();
      
    }//GEN-LAST:event_doneJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        
       String roomNumber = roomNumberJTextField.getText();
        Room room = enterprise.getRoomDirectory().addRoom(roomNumber,Room.RoomType.StorageRoom);
        ((StorageRoom)room).setStorageRoomNumber(roomNumber);
        ((StorageRoom)room).setStorageRoomStatus(status);
        if(status.equals("empty")){
           ((StorageRoom)room).setIsFull(false);
        }
        if(status.equals("Full")){
            ((StorageRoom)room).setIsFull(true);
        }
        populateRoomTable();
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void editJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = storageRoomTable.getSelectedRow();
        if(selectedRow <0 ){
            JOptionPane.showMessageDialog(null, "Please select a row to continue!");
        }
        else{
            roomNumberJLabel.setVisible(true);
            roomNumberJTextField.setVisible(true);
            roomStatusJLabel.setVisible(true);
            emptyJRadioButton.setVisible(true);
            fullJRadioButton.setVisible(true);
            doneJButton.setVisible(true);
            
        }
    }//GEN-LAST:event_editJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateRoomTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton doneJButton;
    private javax.swing.JButton editJButton;
    private javax.swing.JRadioButton emptyJRadioButton;
    private javax.swing.JRadioButton fullJRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noteJLabel;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JLabel roomNumberJLabel;
    private javax.swing.JTextField roomNumberJTextField;
    private javax.swing.JLabel roomStatusJLabel;
    private javax.swing.JTable storageRoomTable;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
