/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.yueli.userinterface.warehouseworkarea;

import java.awt.CardLayout;
import javax.swing.JPanel;
import org.yueli.business.Business;
import org.yueli.business.enterprise.Enterprise;
import org.yueli.business.network.Network;
import org.yueli.business.useraccount.UserAccount;
import org.yueli.userinterface.AppEntrance;

/**
 *
 * @author Lydia
 */
public class WarehouseWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseWorkArea
     */
    private JPanel userProcessContainer;
    private Business business;
    private Network network;
    private Enterprise enterprise;
    private UserAccount userAccount; 
    public WarehouseWorkArea() {
        initComponents();
        this.userProcessContainer = AppEntrance.getSlide();
        this.business = AppEntrance.getBusiness();
        this.userAccount = AppEntrance.getLoginUser();
        userAccount.getNetwork();
        userAccount.getEnterprise();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewDeviceScheduleRequestJButton = new javax.swing.JButton();
        manageStorageRoomJButton = new javax.swing.JButton();
        manageStorageRoomJButton1 = new javax.swing.JButton();

        viewDeviceScheduleRequestJButton.setText("View Device Schedule Request");

        manageStorageRoomJButton.setText("Manage Storage Room");
        manageStorageRoomJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStorageRoomJButtonActionPerformed(evt);
            }
        });

        manageStorageRoomJButton1.setText("Assign Device");
        manageStorageRoomJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStorageRoomJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageStorageRoomJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageStorageRoomJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDeviceScheduleRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(manageStorageRoomJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(manageStorageRoomJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(viewDeviceScheduleRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageStorageRoomJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStorageRoomJButtonActionPerformed
        // TODO add your handling code here:
        ManageRoom manageRoom = new ManageRoom(userProcessContainer, network,enterprise, userAccount);
        userProcessContainer.add("Manage Storage Room", manageRoom);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStorageRoomJButtonActionPerformed

    private void manageStorageRoomJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStorageRoomJButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageStorageRoomJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageStorageRoomJButton;
    private javax.swing.JButton manageStorageRoomJButton1;
    private javax.swing.JButton viewDeviceScheduleRequestJButton;
    // End of variables declaration//GEN-END:variables
}
