/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.yueli.userinterface.supplierworkarea;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.yueli.business.Business;
import org.yueli.business.device.Device;
import org.yueli.business.inventory.InventoryItem;
import org.yueli.business.network.Network;
import org.yueli.business.organization.Organization;
import org.yueli.business.organization.SupplierOrganization;
import static org.yueli.business.role.Role.RoleType.SupplierAdmin;
import org.yueli.business.role.SupplierAdmin;
import org.yueli.business.useraccount.UserAccount;

/**
 *
 * @author Lydia
 */
public class CreateNewDevice extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewDevice
     */
    private JPanel userProcessContainer;
    private Business business;
    private UserAccount userAccount;
    private Network network;
    private Organization organization;
    public CreateNewDevice(JPanel userProcessContainer, Business business, UserAccount userAccount, Network network, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.network = network;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deviceFunctionJTextField = new javax.swing.JTextField();
        deviceNameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        unitPriceJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        descriptionJTextField = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();

        jLabel1.setText("Device Name: ");

        jLabel2.setText("Device Function:");

        jLabel6.setText("Unit Price:");

        jLabel11.setText("Description:");

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createJButton)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel11)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deviceNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(deviceFunctionJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(unitPriceJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(descriptionJTextField))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deviceNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deviceFunctionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(unitPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(createJButton)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
       //InventoryItem inventoryItem = ((SupplierOrganization)organization).getDeviceCatalog().addDevice();
        Device device = ((SupplierOrganization)organization).getDeviceCatalog().addDevice();
        device.setDeviceName(deviceNameJTextField.getText());
        device.setFunction(deviceFunctionJTextField.getText());
        
        if(unitPriceJTextField.getText().isEmpty()==false){
            device.setDevicePrice(Integer.parseInt(unitPriceJTextField.getText()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Please enter a valid price", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        device.setDescription(descriptionJTextField.getText());
        device.setSupplierID(((SupplierOrganization)organization).getSupplierID());
        device.setSupplierName(((SupplierOrganization)organization).getSupplierName());
        InventoryItem inventoryItem = (((SupplierOrganization)organization).getInventory().addInventoryItem());
        inventoryItem.setDevice(device);
    }//GEN-LAST:event_createJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createJButton;
    private javax.swing.JTextField descriptionJTextField;
    private javax.swing.JTextField deviceFunctionJTextField;
    private javax.swing.JTextField deviceNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField unitPriceJTextField;
    // End of variables declaration//GEN-END:variables
}
