/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.yueli.userinterface.supplierworkarea;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.yueli.business.Business;
import org.yueli.business.enterprise.Enterprise;
import org.yueli.business.enterprise.HospitalEnterprise;
import org.yueli.business.enterprise.PrimaryCare;
import org.yueli.business.inventory.Inventory;
import org.yueli.business.inventory.InventoryItem;
import org.yueli.business.network.Network;
import org.yueli.business.order.Order;
import org.yueli.business.order.OrderItem;
import org.yueli.business.organization.Organization;
import org.yueli.business.role.FAMCAdmin;
import org.yueli.business.role.HospitalAdmin;
import org.yueli.business.role.PrimaryCareAdmin;
import org.yueli.business.role.Role;
import org.yueli.business.useraccount.UserAccount;
import org.yueli.business.workqueue.OrderRequest;
import org.yueli.business.workqueue.WorkQueue;
import org.yueli.business.workqueue.WorkRequest;

/**
 *
 * @author Lydia
 */
public class ViewOrder extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrder
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Business business;
    private Network network;
    private Organization organization;
    
    public ViewOrder(JPanel userProcessContainer, UserAccount userAccount,Business business, Network network, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.network = network;
        this.organization = organization;
        //populateEnterpriseTypeCombo();
        populateOrderTable();
    }
    
//    public void populateEnterpriseTypeCombo(){
//        enterpriseJCombo.removeAllItems();
//        
//        
//            for(Enterprise enterprise : network.getEnterpriseList().getEnterpriseList())
//                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList() ){
//                    for(UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountList()){
//                        enterpriseJCombo.addItem(userAccount);
//                    }
//                }
//            
//        }
//    
    
    public void populateOrderTable(){
        
        DefaultTableModel model = (DefaultTableModel)orderJTable.getModel();
        model.setRowCount(0);
        
       for(WorkRequest workRequest :organization.getWorkQueue().getWorkRequestList() ) {
           if(workRequest instanceof OrderRequest){
                Object row[] = new Object[2];
                row[0] = ((OrderRequest)workRequest);
                row[1] = ((OrderRequest)workRequest).getOrder().getOrderID();
                model.addRow(row); 
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderDetailJTable = new javax.swing.JTable();
        viewJButton = new javax.swing.JButton();
        approveJButton = new javax.swing.JButton();
        declineJButton = new javax.swing.JButton();

        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Order ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderJTable);
        if (orderJTable.getColumnModel().getColumnCount() > 0) {
            orderJTable.getColumnModel().getColumn(0).setResizable(false);
            orderJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        orderDetailJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device Name", "Quantity", "Unit Price", "Total Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderDetailJTable);
        if (orderDetailJTable.getColumnModel().getColumnCount() > 0) {
            orderDetailJTable.getColumnModel().getColumn(0).setResizable(false);
            orderDetailJTable.getColumnModel().getColumn(1).setResizable(false);
            orderDetailJTable.getColumnModel().getColumn(2).setResizable(false);
            orderDetailJTable.getColumnModel().getColumn(3).setResizable(false);
            orderDetailJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        viewJButton.setText("View");
        viewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJButtonActionPerformed(evt);
            }
        });

        approveJButton.setText("Approve");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });

        declineJButton.setText("Decline");
        declineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(viewJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(approveJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(declineJButton)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(viewJButton)))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveJButton)
                    .addComponent(declineJButton))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJButtonActionPerformed
        // TODO add your handling code here:
        
      
        int selectedRow = orderJTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "Please select a row to view!");
        }
        else{
            OrderRequest orderRequest = (OrderRequest)orderJTable.getValueAt(selectedRow, 0);
            DefaultTableModel model = (DefaultTableModel)orderDetailJTable.getModel();
            model.setRowCount(0);
            for(OrderItem orderItem : orderRequest.getOrder().getOrderItemList()){
                Object row[] = new Object[5];
                row[0] = orderItem;
                row[1] = orderItem.getOrderQuantity();
                row[2] = orderItem.getInventoryItem().getDevice().getDevicePrice();
                row[3] = orderItem.getInventoryItem().getDevice().getDevicePrice() * orderItem.getOrderQuantity();
                row[4] = orderRequest.getOrderStatus();
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_viewJButtonActionPerformed

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderJTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "Please select a row to continue!");
        }
        else{
            OrderRequest orderRequest = (OrderRequest)orderJTable.getValueAt(selectedRow, 0);
            orderRequest.setOrderStatus("Completed");
            Enterprise enterprise = orderRequest.getSender().getEnterprise();
            for(OrderItem orderItem : orderRequest.getOrder().getOrderItemList()){
                orderItem.getInventoryItem().getDevice().setIsAssigned(false);
                if (enterprise instanceof HospitalEnterprise) {
                    ((HospitalEnterprise)enterprise).getInventory().getInventoryItemList().add(orderItem.getInventoryItem());
                }
            }
        }
    }//GEN-LAST:event_approveJButtonActionPerformed

    private void declineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderJTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "Please select a row to continue!");
        }
        else{
            OrderRequest orderRequest = (OrderRequest)orderJTable.getValueAt(selectedRow, 0);
            orderRequest.setOrderStatus("Canceled");
            
        }
    }//GEN-LAST:event_declineJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveJButton;
    private javax.swing.JButton declineJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderDetailJTable;
    private javax.swing.JTable orderJTable;
    private javax.swing.JButton viewJButton;
    // End of variables declaration//GEN-END:variables
}
